server:
  port: 42500

spring:
  application:
    name: dokha-backend
  datasource:
    driverClassName: org.postgresql.Driver
    username: dokha
    password: dokha
    url: jdbc:postgresql://localhost:5432/dokha
  flyway:
    schemas: dokha
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  signingKey: dokha42
  header: X-Auth-Token
  accessTokenValidityMillisecond: 31556926 # год

testUser:
  login: test
  password: password


---

spring:
  profiles: test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:dokha;INIT=CREATE SCHEMA IF NOT EXISTS DOKHA
    username: dokha
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show_sql: false

---